// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Appostolic.Api.Infrastructure;

namespace Appostolic.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250923153000_s8_01_refresh_sessions")]
partial class s8_01_refresh_sessions
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // NOTE: This designer file is intentionally minimal for Story 8 migration context.
        // Full model snapshot remains authoritative.
    }
}