// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Appostolic.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250915173000_s4_03_audits_view")]
    partial class s4_03_audits_view
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Keep model snapshot consistent; no schema changes beyond the SQL view
            // NOTE: Views are created via raw SQL and not represented as DbSet entities.

            // Include minimal entities to satisfy EF snapshot consistency during migration
            modelBuilder.Entity("Appostolic.Api.Audit", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTime>("ChangedAt").HasColumnType("timestamp with time zone").HasColumnName("changed_at");
                    b.Property<string>("ChangedByEmail").HasColumnType("text").HasColumnName("changed_by_email");
                    b.Property<Guid?>("ChangedByUserId").HasColumnType("uuid").HasColumnName("changed_by_user_id");
                    b.Property<int>("NewRoles").HasColumnType("integer").HasColumnName("new_roles");
                    b.Property<int>("OldRoles").HasColumnType("integer").HasColumnName("old_roles");
                    b.Property<Guid>("TenantId").HasColumnType("uuid").HasColumnName("tenant_id");
                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "ChangedAt").HasDatabaseName("ix_audits_tenant_changed");
                    b.ToTable("audits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
