// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Appostolic.Api.Infrastructure;

namespace Appostolic.Api.Migrations;

/// <summary>
/// Designer stub for Story 11 migration (adds original_created_at to refresh_tokens).
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("20250924120000_s11_01_refresh_original_created")]
public partial class s11_01_refresh_original_created
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Intentionally elided. AppDbContextModelSnapshot remains the source of truth for the model graph.
    }
}
