# Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./apps/api/*.csproj ./
RUN dotnet restore ./Appostolic.Api.csproj
COPY ./apps/api/. ./
RUN dotnet publish ./Appostolic.Api.csproj -c Release -o /app

# Run
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Appostolic.Api.dll"]
