name: API E2E Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-api-e2e:
    name: dotnet test (apps/api.tests)
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore
        run: dotnet restore appostolic.sln

      - name: Build
        run: dotnet build appostolic.sln --no-restore -c Release

      - name: Test (API E2E)
        run: |
          mkdir -p artifacts/test-results artifacts/coverage
          dotnet test apps/api.tests/Appostolic.Api.Tests.csproj \
            --no-build -c Release \
            --results-directory artifacts/test-results \
            --logger "trx;LogFileName=api-e2e.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutput=artifacts/coverage/ \
            /p:CoverletOutputFormat=cobertura

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-e2e-test-results
          path: artifacts/test-results

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-e2e-coverage
          path: artifacts/coverage
